//! Build script for cc-protocol
//!
//! Generates type-safe Rust bindings from strudel_api_references.csv

use std::env;
use std::fs::{self, File};
use std::io::{BufRead, BufReader, Write};
use std::path::Path;

fn main() {
    // Tell Cargo to re-run if CSV changes
    println!("cargo:rerun-if-changed=strudel_api_references.csv");

    // Only generate if CSV exists
    let csv_path = "strudel_api_references.csv";
    if !Path::new(csv_path).exists() {
        eprintln!("Warning: {} not found, skipping code generation", csv_path);
        return;
    }

    // Parse CSV and generate code
    match generate_strudel_api(csv_path) {
        Ok(()) => println!("Successfully generated Strudel API bindings"),
        Err(e) => eprintln!("Warning: Failed to generate Strudel API: {}", e),
    }
}

#[derive(Debug)]
struct StrudelFunction {
    name: String,
    description: String,
    synonyms: String,
    #[allow(dead_code)]
    params: String,
    #[allow(dead_code)]
    returns: String,
    examples: String,
}

fn generate_strudel_api(csv_path: &str) -> Result<(), Box<dyn std::error::Error>> {
    let file = File::open(csv_path)?;
    let reader = BufReader::new(file);
    let mut functions = Vec::new();

    // Skip header line
    let mut lines = reader.lines();
    lines.next();

    // Parse CSV (format: name,synonyms,synonyms_text,description,params,returns,examples)
    for line in lines {
        let line = line?;
        if line.trim().is_empty() {
            continue;
        }

        // Simple CSV parsing - split on comma but this will fail for quoted fields
        // For now, just collect the basic info we can reliably parse
        let parts: Vec<&str> = line.splitn(7, ',').collect();
        if parts.is_empty() || parts[0].trim().is_empty() {
            continue;
        }

        let func = StrudelFunction {
            name: parts.get(0).map(|s| s.trim().to_string()).unwrap_or_default(),
            synonyms: parts.get(1).map(|s| s.trim().to_string()).unwrap_or_default(),
            description: parts.get(3).map(|s| s.trim().to_string()).unwrap_or_default(),
            params: parts.get(4).map(|s| s.to_string()).unwrap_or_default(),
            returns: parts.get(5).map(|s| s.to_string()).unwrap_or_default(),
            examples: parts.get(6).map(|s| s.to_string()).unwrap_or_default(),
        };

        if !func.name.is_empty() {
            functions.push(func);
        }
    }

    // Generate Rust code
    let out_dir = env::var("OUT_DIR")?;
    let dest_path = Path::new(&out_dir).join("strudel_api_generated.rs");
    let mut output = File::create(&dest_path)?;

    write_header(&mut output)?;
    write_function_registry(&mut output, &functions)?;
    write_helpers(&mut output, &functions)?;

    println!("Generated {} Strudel API functions", functions.len());
    Ok(())
}

fn write_header(output: &mut File) -> std::io::Result<()> {
    writeln!(output, "// Generated by build.rs - DO NOT EDIT")?;
    writeln!(output, "// Source: strudel_api_references.csv")?;
    writeln!(output)?;
    Ok(())
}

fn write_function_registry(output: &mut File, functions: &[StrudelFunction]) -> std::io::Result<()> {
    writeln!(output, "/// Strudel function metadata")?;
    writeln!(output, "#[derive(Debug, Clone)]")?;
    writeln!(output, "pub struct StrudelFunctionInfo {{")?;
    writeln!(output, "    pub name: &'static str,")?;
    writeln!(output, "    pub description: &'static str,")?;
    writeln!(output, "    pub synonyms: &'static str,")?;
    writeln!(output, "    pub examples: &'static str,")?;
    writeln!(output, "}}")?;
    writeln!(output)?;

    writeln!(output, "/// All {} Strudel API functions", functions.len())?;
    writeln!(output, "pub const STRUDEL_FUNCTIONS: &[(&str, &str)] = &[")?;

    for func in functions {
        let name = func.name.replace('\\', "\\\\").replace('"', "\\\"");
        let desc = func.description.replace('\\', "\\\\").replace('"', "\\\"").replace('\n', " ");
        writeln!(output, "    (\"{}\", \"{}\"),", name, desc)?;
    }

    writeln!(output, "];")?;
    writeln!(output)?;

    Ok(())
}

fn write_helpers(output: &mut File, functions: &[StrudelFunction]) -> std::io::Result<()> {
    writeln!(output, "/// Get total number of Strudel API functions")?;
    writeln!(output, "pub const STRUDEL_FUNCTION_COUNT: usize = {};", functions.len())?;
    writeln!(output)?;

    writeln!(output, "/// Check if a function name is valid")?;
    writeln!(output, "pub fn is_valid_strudel_function(name: &str) -> bool {{")?;
    writeln!(output, "    STRUDEL_FUNCTIONS.iter().any(|(n, _)| *n == name)")?;
    writeln!(output, "}}")?;
    writeln!(output)?;

    Ok(())
}

fn sanitize_enum_name(s: &str) -> String {
    // Convert category name to valid Rust enum variant
    let mut result = String::new();
    let mut capitalize_next = true;

    for c in s.chars() {
        if c.is_alphanumeric() {
            if capitalize_next {
                result.push_str(&c.to_uppercase().to_string());
                capitalize_next = false;
            } else {
                result.push(c);
            }
        } else {
            capitalize_next = true;
        }
    }

    // Ensure it starts with uppercase
    if result.is_empty() {
        return "Unknown".to_string();
    }

    // Ensure it doesn't start with a number
    if result.chars().next().unwrap().is_numeric() {
        result = format!("Category{}", result);
    }

    result
}

fn escape_string(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_sanitize_enum_name() {
        assert_eq!(sanitize_enum_name("pattern"), "Pattern");
        assert_eq!(sanitize_enum_name("time & rhythm"), "TimeRhythm");
        assert_eq!(sanitize_enum_name("fx/audio"), "FxAudio");
        assert_eq!(sanitize_enum_name("123invalid"), "Category123invalid");
    }

    #[test]
    fn test_escape_string() {
        assert_eq!(escape_string("hello \"world\""), "hello \\\"world\\\"");
        assert_eq!(escape_string("line1\nline2"), "line1\\nline2");
    }
}
